Repository prinz-nussknacker/prinz, pull requests merged in 2020-11, with the labels that each got.

#11 Add docker version of mlflow env
  dev-environment/clear_environment.sh
  dev-environment/create_environment.sh
  dev-environment/docker-compose.yml
  dev-environment/mlflow/Dockerfile
  dev-environment/mlflow/run.sh
  dev-environment/stop_environment.sh
Labels: enhancement

#14 Add docker with Nussknacker
  dev-environment/create_environment.sh
  dev-environment/docker-compose.yml
  dev-environment/mlflow/Dockerfile
  dev-environment/mlflow/artifact-store/.gitkeep
  dev-environment/nussknacker/Dockerfile
  dev-environment/nussknacker/run.sh
Labels: enhancement

#16 Update scalastyle rules
  .github/workflows/code_quality.yaml
  project/scalastyle_config.xml
Labels: enhancement

#19 Add registered model served by mlflow as example model on port 1234
  .gitignore
  dev-environment/docker-compose.yml
  dev-environment/minio/.gitkeep
  dev-environment/mlflow/Dockerfile
  dev-environment/mlflow/models/sklearn_elasticnet_wine/MLproject
  dev-environment/mlflow/models/sklearn_elasticnet_wine/conda.yaml
  dev-environment/mlflow/models/sklearn_elasticnet_wine/train.py
  dev-environment/mlflow/models/sklearn_elasticnet_wine/wine-quality.csv
  dev-environment/mlflow/run.sh
  dev-environment/nussknacker/Dockerfile
Labels: enhancement

#25 Add yaml file checker
  .github/workflows/code_quality.yaml
  .gitignore
  dev-environment/docker-compose.yaml
  dev-environment/minio/.gitkeep
  dev-environment/minio/Dockerfile
  dev-environment/minio/run.sh
  dev-environment/mlflow/models/sklearn_elasticnet_wine/conda.yaml
  dev-environment/nussknacker/Dockerfile
Labels: enhancement

#34 Added README
  .github/scripts/trailing_whitespace_check.sh
  .github/workflows/code_quality.yaml
  README.md
  docs/imgs/nussknacker_operation_model.png
  docs/imgs/prinz_internal_model.png
Labels: documentation

#29 Model api #21
  .gitignore
  build.sbt
  prinz/src/main/scala/pl/touk/nussknacker/prinz/mlflow/MlflowConstants.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/mlflow/model/MLFModelInstance.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/mlflow/model/RegisteredModel.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/mlflow/model/RestModelRunException.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/mlflow/repository/MLFRepositoryRestClient.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/mlflow/repository/MLFRepositoryRestException.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/model/Model.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/model/ModelInstance.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/model/ModelRunException.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/model/repository/ModelRepository.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/model/repository/ModelRepositoryException.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/exceptions/PrinzException.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/http/RequestParams.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/http/RestClientException.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/http/RestJsonClient.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/reflect/ReflectFields.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/reflect/ReflectMethods.scala
Labels: enhancement

#36 Add model signature to served model
  dev-environment/mlflow/Dockerfile
  dev-environment/mlflow/models/sklearn_elasticnet_wine/train.py
Labels: enhancement

#38 Collections implementation
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/collection/MultiMap.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/collection/immutable/MapMultiset.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/collection/immutable/MultiTreeMap.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/collection/immutable/SetMultimap.scala
  prinz/src/test/scala/pl/touk/nussknacker/prinz/converter/mlflow/MlflowDataConverterTest.scala
  prinz/src/test/scala/pl/touk/nussknacker/prinz/util/collection/immutable/MapMultisetTest.scala
  prinz/src/test/scala/pl/touk/nussknacker/prinz/util/collection/immutable/MultiTreeMapTest.scala
  prinz/src/test/scala/pl/touk/nussknacker/prinz/util/collection/immutable/SetMultimapTest.scala
Labels: enhancement

#47 Fix workflow run to include checkstyle
  .github/workflows/code_quality.yaml
  .github/workflows/unit_tests.yaml
  prinz/src/main/scala/pl/touk/nussknacker/prinz/mlflow/model/MLFModelInstance.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/collection/immutable/MapMultiset.scala
  prinz/src/main/scala/pl/touk/nussknacker/prinz/util/collection/immutable/SetMultimap.scala
  project/scalastyle_config.xml
Labels: bug
